language: node_js

os:
  - linux

node_js:
  - 'stable'

notifications:
  slack: publicstrategiesgroup:SIDj5XVLcpknbHdCue6JA4nJ

cache:
  directories:
    - node_modules

script:
  - npm run validate
  - npm run test-ci
